import {
  type SimpleIcon,
  siAngular,
  siApacheairflow,
  siBootstrap,
  siClaude,
  siCss,
  siCypress,
  siDocker,
  siElixir,
  siExpress,
  siFastapi,
  siGit,
  siGithubactions,
  siGitlab,
  siGo,
  siHtml5,
  siJavascript,
  siJest,
  siJetpackcompose,
  siKotlin,
  siKubernetes,
  siLaravel,
  siLinux,
  siModelcontextprotocol,
  siMongodb,
  siNette,
  siNextdotjs,
  siNginx,
  siNodedotjs,
  siNumpy,
  siNuxt,
  siOpencv,
  siOpenjdk,
  siP5dotjs,
  siPandas,
  siPhoenixframework,
  siPhp,
  siPlotly,
  siPostgresql,
  siPython,
  siPytorch,
  siReact,
  siReactrouter,
  siRedis,
  siRedux,
  siRuby,
  siSelenium,
  siSpringboot,
  siStencil,
  siTailwindcss,
  siTanstack,
  siTensorflow,
  siTypescript,
  siUnity,
  siVite,
  siVitest,
  siVuedotjs,
  siZod,
} from "simple-icons";

/**
 * Logos for technology names used in the content. Names without an entry
 * (e.g. C#, MSSQL, Playwright, whose brands are not in Simple Icons) show text only.
 */
const icons: Record<string, SimpleIcon> = {
  Airflow: siApacheairflow,
  Angular: siAngular,
  Bootstrap: siBootstrap,
  "Claude Code": siClaude,
  "Compose Multiplatform": siJetpackcompose,
  CSS: siCss,
  Cypress: siCypress,
  Docker: siDocker,
  Elixir: siElixir,
  Express: siExpress,
  FastAPI: siFastapi,
  Git: siGit,
  "GitHub Actions": siGithubactions,
  "GitLab CI": siGitlab,
  Go: siGo,
  HTML: siHtml5,
  Java: siOpenjdk,
  JavaScript: siJavascript,
  Jest: siJest,
  Kotlin: siKotlin,
  "Kotlin Multiplatform": siKotlin,
  Kubernetes: siKubernetes,
  Laravel: siLaravel,
  Linux: siLinux,
  MCP: siModelcontextprotocol,
  MongoDB: siMongodb,
  Nette: siNette,
  "Next.js": siNextdotjs,
  nginx: siNginx,
  "Node.js": siNodedotjs,
  NumPy: siNumpy,
  Nuxt: siNuxt,
  OpenCV: siOpencv,
  "p5.js": siP5dotjs,
  pandas: siPandas,
  Phoenix: siPhoenixframework,
  "Phoenix LiveView": siPhoenixframework,
  PHP: siPhp,
  Plotly: siPlotly,
  PostgreSQL: siPostgresql,
  Python: siPython,
  PyTorch: siPytorch,
  React: siReact,
  "React Query": siTanstack,
  "React Router": siReactrouter,
  Redis: siRedis,
  Redux: siRedux,
  Ruby: siRuby,
  Selenium: siSelenium,
  "Spring Boot": siSpringboot,
  "Stencil.js": siStencil,
  "Tailwind CSS": siTailwindcss,
  TanStack: siTanstack,
  "TanStack Query": siTanstack,
  TensorFlow: siTensorflow,
  TypeScript: siTypescript,
  Unity: siUnity,
  Vite: siVite,
  Vitest: siVitest,
  Vue: siVuedotjs,
  Zod: siZod,
};

export function techIcon(name: string) {
  return icons[name];
}
