import type { SkillGroup } from "./types";

export const skillGroups: SkillGroup[] = [
  {
    name: "Daily",
    description: "What I work with every day.",
    skills: [
      "TypeScript",
      "React",
      "Kotlin",
      "Spring Boot",
      "TanStack Router",
      "TanStack Query",
      "TanStack Form",
      "TanStack Table",
      "TanStack Virtual",
      "Tailwind CSS",
      "PostgreSQL",
      "Git",
    ],
  },
  {
    name: "Mobile",
    description: "Shared Kotlin code for Android and iOS.",
    skills: ["Kotlin Multiplatform", "Compose Multiplatform", "Ktor", "Koin"],
  },
  {
    name: "Worked with",
    description: "Used in real projects and comfortable picking up again.",
    skills: [
      "Python",
      "Elixir",
      "Phoenix LiveView",
      "Node.js",
      "Express",
      "PHP",
      "Laravel",
      "Nette",
      "Next.js",
      "Vue",
      "Nuxt",
      "MongoDB",
      "MSSQL",
      "Zod",
      "Vitest",
      "Jest",
      "Playwright",
      "Cypress",
      "GitLab CI",
      "Docker Compose",
      "Airflow",
      "Ruby",
      "Linux",
    ],
  },
  {
    name: "AI and machine learning",
    description: "From my master's thesis and product integrations.",
    skills: ["PyTorch", "TensorFlow", "OpenCV", "OpenAI API"],
  },
  {
    name: "Tools",
    description: "How I build day to day.",
    skills: ["Claude Code", "Agent skills", "MCP servers", "Figma", "Jira"],
  },
  {
    name: "Familiar",
    description: "Tried in smaller projects or at university.",
    skills: ["Java", "C#", "Django", "FastAPI", "Redis", "Bootstrap", "Go", "Kubernetes", "Unity"],
  },
];
